packages:
  - apps/*
  - packages/*
exclude:
  - "**/dist"
  - "**/build"
  - "**/__tests__/**"
  - "**/*.test.*"
  - "**/node_modules"
  - "**/.turbo"
  - "**/.cache"
  - "**/temp"
  - "**/tmp"
  - "**/logs"
  - "**/.debug"
  - "**/.vscode"
  - "**/.idea"
  - "**/coverage"
  - "**/.env.*"
catalog:
  "@antfu/eslint-config": ^6.7.3
  "@iconify-json/carbon": ^1.2.15
  "@iconify-json/ep": ^1.2.3
  "@iconify-json/mdi": ^1.2.3
  "@tanstack/vue-query": ^5.92.1
  "@types/archiver": ^7.0.0
  "@types/node": ^25.0.3
  "@types/nprogress": ^0.2.3
  "@types/splitpanes": ^2.2.6
  "@unocss/eslint-plugin": ^66.5.10
  "@unocss/reset": ^66.5.10
  "@vant/auto-import-resolver": ^1.3.0
  "@vitejs/plugin-vue": ^6.0.3
  "@vueuse/core": ^14.1.0
  archiver: ^7.0.1
  axios: ^1.13.2
  code-inspector-plugin: ^1.3.4
  element-plus: ^2.13.0
  eslint: ^9.39.2
  eslint-plugin-format: ^1.1.0
  lib-flexible: ^0.3.2
  nprogress: ^0.2.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  postcss-preset-env: ^10.5.0
  postcss-pxtorem: ^6.1.0
  splitpanes: ^4.0.4
  "@wangeditor-next/editor": ^5.6.49
  "@wangeditor-next/editor-for-vue": ^5.1.14
  turbo: ^2.7.2
  typescript: ^5.9.3
  unbuild: ^3.6.1
  universal-cookie: ^8.0.1
  unocss: ^66.5.10
  unplugin-auto-import: ^20.3.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-router: ^0.19.1
  vant: ^4.9.22
  vite: ^7.3.0
  vite-plugin-compression: ^0.5.1
  vite-plugin-vue-devtools: ^8.0.5
  vite-plugin-zip-pack: ^1.2.4
  vue: ^3.5.26
  vue-router: ^4.6.4
  vue-tsc: ^3.2.1
