packages:
  - apps/*
  - packages/*
exclude:
  - "**/dist"
  - "**/build"
  - "**/__tests__/**"
  - "**/*.test.*"
  - "**/node_modules"
  - "**/.turbo"
  - "**/.cache"
  - "**/temp"
  - "**/tmp"
  - "**/logs"
  - "**/.debug"
  - "**/.vscode"
  - "**/.idea"
  - "**/coverage"
  - "**/.env.*"
catalog:
  "@antfu/eslint-config": ^4.14.1
  "@iconify-json/carbon": ^1.2.9
  "@iconify-json/ep": ^1.2.2
  "@iconify-json/mdi": ^1.2.3
  "@tanstack/vue-query": ^5.80.6
  "@types/archiver": ^6.0.3
  "@types/node": ^22.15.31
  "@types/nprogress": ^0.2.3
  "@types/splitpanes": ^2.2.6
  "@unocss/eslint-plugin": ^66.1.4
  "@unocss/reset": ^66.1.4
  "@vant/auto-import-resolver": ^1.3.0
  "@vitejs/plugin-vue": ^5.2.4
  "@vueuse/core": ^13.3.0
  archiver: ^7.0.1
  axios: ^1.9.0
  code-inspector-plugin: ^0.20.12
  element-plus: ^2.10.1
  eslint: ^9.28.0
  eslint-plugin-format: ^1.0.1
  lib-flexible: ^0.3.2
  nprogress: ^0.2.0
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.3.0
  postcss-preset-env: ^10.2.2
  postcss-pxtorem: ^6.1.0
  quill: 2.0.3
  splitpanes: ^4.0.4
  turbo: ^2.5.4
  typescript: ^5.8.3
  unbuild: ^3.5.0
  universal-cookie: ^8.0.1
  unocss: ^66.1.4
  unplugin-auto-import: ^19.3.0
  unplugin-vue-components: ^28.7.0
  unplugin-vue-router: ^0.12.0
  vant: ^4.9.19
  vite: ^6.3.5
  vite-plugin-compression: ^0.5.1
  vite-plugin-vue-devtools: ^7.7.6
  vite-plugin-zip-pack: ^1.2.4
  vue: ^3.5.16
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
