packages:
  # 应用目录
  - 'apps/*'
  # 共享包目录
  - 'packages/*'

# 排除以下目录和文件
exclude:
  # 构建输出目录
  - '**/dist'
  - '**/build'
  # 测试目录
  - '**/__tests__/**'
  - '**/*.test.*'
  # 缓存目录
  - '**/node_modules'
  - '**/.turbo'
  - '**/.cache'
  # 临时文件
  - '**/temp'
  - '**/tmp'
  # 日志文件
  - '**/logs'
  # 调试文件
  - '**/.debug'
  # IDE 配置文件
  - '**/.vscode'
  - '**/.idea'
  # 其他
  - '**/coverage'
  - '**/.env.*'
catalog:
  "@antfu/eslint-config": "^4.12.0"
  "@types/archiver": "^6.0.3"
  "@types/node": "^22.14.1"
  "@unocss/eslint-plugin": "^66.0.0"
  "@unocss/reset": "^66.0.0"
  "@vitejs/plugin-vue": "^5.2.3"
  "archiver": "^7.0.1"
  "code-inspector-plugin": "^0.20.10"
  "eslint": "^9.25.0"
  "eslint-plugin-format": "^1.0.1"
  "turbo": "^2.5.1"
  "typescript": "^5.8.3"
  "unocss": "^66.0.0"
  "unplugin-auto-import": "^19.1.2"
  "unplugin-vue-components": "^28.5.0"
  "vite": "^6.3.2"
  "vite-plugin-compression": "^0.5.1"
  "vite-plugin-zip-pack": "^1.2.4"
  "vue-tsc": "^2.2.8"
  "unbuild": "^3.5.0"
  "alova": "^3.2.10"
  "@iconify-json/carbon": "^1.2.8"
  "@iconify-json/ep": "^1.2.2"
  "@iconify-json/mdi": "^1.2.3"
  "pinia-plugin-persistedstate": "^4.2.0"
  "vant": "^4.9.19"
  "@vant/auto-import-resolver": "^1.3.0"
  "lib-flexible": "^0.3.2"
  "postcss-pxtorem": "^6.1.0"
  "unplugin-vue-router": "^0.12.0"
  "@types/nprogress": "^0.2.3"
  "@types/splitpanes": "^2.2.6"
  "element-plus": "^2.9.8"
  "nprogress": "^0.2.0"
  "quill": "2.0.3"
  "splitpanes": "^4.0.3"
  "universal-cookie": "^8.0.1"
