packages:
  - apps/*
  - packages/*
exclude:
  - "**/dist"
  - "**/build"
  - "**/__tests__/**"
  - "**/*.test.*"
  - "**/node_modules"
  - "**/.turbo"
  - "**/.cache"
  - "**/temp"
  - "**/tmp"
  - "**/logs"
  - "**/.debug"
  - "**/.vscode"
  - "**/.idea"
  - "**/coverage"
  - "**/.env.*"
catalog:
  "@antfu/eslint-config": ^6.2.0
  "@iconify-json/carbon": ^1.2.14
  "@iconify-json/ep": ^1.2.3
  "@iconify-json/mdi": ^1.2.3
  "@tanstack/vue-query": ^5.90.7
  "@types/archiver": ^7.0.0
  "@types/node": ^24.10.0
  "@types/nprogress": ^0.2.3
  "@types/splitpanes": ^2.2.6
  "@unocss/eslint-plugin": ^66.5.5
  "@unocss/reset": ^66.5.5
  "@vant/auto-import-resolver": ^1.3.0
  "@vitejs/plugin-vue": ^6.0.1
  "@vueuse/core": ^14.0.0
  archiver: ^7.0.1
  axios: ^1.13.2
  code-inspector-plugin: ^1.2.10
  element-plus: ^2.11.7
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  lib-flexible: ^0.3.2
  nprogress: ^0.2.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  postcss-preset-env: ^10.4.0
  postcss-pxtorem: ^6.1.0
  splitpanes: ^4.0.4
  "@wangeditor-next/editor": ^5.6.47
  "@wangeditor-next/editor-for-vue": ^5.1.14
  turbo: ^2.6.0
  typescript: ^5.9.3
  unbuild: ^3.6.1
  universal-cookie: ^8.0.1
  unocss: ^66.5.5
  unplugin-auto-import: ^20.2.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-router: ^0.16.1
  vant: ^4.9.21
  vite: ^7.2.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-vue-devtools: ^8.0.3
  vite-plugin-zip-pack: ^1.2.4
  vue: ^3.5.24
  vue-router: ^4.6.3
  vue-tsc: ^3.1.3
