packages:
  - apps/*
  - packages/*
exclude:
  - "**/dist"
  - "**/build"
  - "**/__tests__/**"
  - "**/*.test.*"
  - "**/node_modules"
  - "**/.turbo"
  - "**/.cache"
  - "**/temp"
  - "**/tmp"
  - "**/logs"
  - "**/.debug"
  - "**/.vscode"
  - "**/.idea"
  - "**/coverage"
  - "**/.env.*"
catalog:
  "@antfu/eslint-config": ^4.12.0
  "@iconify-json/carbon": ^1.2.8
  "@iconify-json/ep": ^1.2.2
  "@iconify-json/mdi": ^1.2.3
  "@tanstack/vue-query": ^5.74.7
  "@types/archiver": ^6.0.3
  "@types/node": ^22.14.1
  "@types/nprogress": ^0.2.3
  "@types/splitpanes": ^2.2.6
  "@unocss/eslint-plugin": ^66.0.0
  "@unocss/reset": ^66.0.0
  "@vant/auto-import-resolver": ^1.3.0
  "@vitejs/plugin-vue": ^5.2.3
  "@vueuse/core": ^13.1.0
  archiver: ^7.0.1
  axios: ^1.9.0
  code-inspector-plugin: ^0.20.10
  element-plus: ^2.9.8
  eslint: ^9.25.0
  eslint-plugin-format: ^1.0.1
  lib-flexible: ^0.3.2
  nprogress: ^0.2.0
  pinia: ^3.0.2
  pinia-plugin-persistedstate: ^4.2.0
  postcss-preset-env: ^10.1.6
  postcss-pxtorem: ^6.1.0
  quill: 2.0.3
  splitpanes: ^4.0.3
  turbo: ^2.5.1
  typescript: ^5.8.3
  unbuild: ^3.5.0
  universal-cookie: ^8.0.1
  unocss: ^66.0.0
  unplugin-auto-import: ^19.1.2
  unplugin-vue-components: ^28.5.0
  unplugin-vue-router: ^0.12.0
  vant: ^4.9.19
  vite: ^6.3.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-zip-pack: ^1.2.4
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
