name: Auto PR to Main (Owner Only)

on:
  push:
    branches-ignore:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the actor is the repository owner
        id: check-owner
        run: |
          owner=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          if [ "${{ github.actor }}" != "$owner" ]; then
            echo "This push was made by ${{ github.actor }}, not the repository owner ($owner)."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-pr
        run: |
          branch_name=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          pr_url=$(gh pr create \
            --base main \
            --head "$branch_name" \
            --title "Auto PR: Merge $branch_name into main" \
            --body "This PR was automatically created to merge changes from $branch_name into main." || echo "conflict")
          echo "pr_url=$pr_url" >> $GITHUB_ENV

      - name: Assign PR to Repository Owner (if conflict)
        if: env.pr_url == "conflict"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          owner=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          branch_name=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          gh pr create \
            --base main \
            --head "$branch_name" \
            --title "Auto PR: Merge $branch_name into main" \
            --body "This PR was automatically created to merge changes from $branch_name into main. **However, it has conflicts. Please review and resolve them.**"
          pr_number=$(gh pr list --state open --head "$branch_name" --json number -q '.[0].number')
          gh pr edit "$pr_number" --add-assignee "$owner"
