/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    Description: typeof import('./../src/components/Description.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    IFrame: typeof import('./../src/components/IFrame.vue')['default']
    ImagePreview: typeof import('./../src/components/ImagePreview.vue')['default']
    ImageUpload: typeof import('./../src/components/ImageUpload.vue')['default']
    ListPage: typeof import('./../src/components/ListPage.vue')['default']
    MoreOperte: typeof import('./../src/components/SimpleTable/MoreOperte.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollView: typeof import('./../src/components/ScrollView.vue')['default']
    SimpleForm: typeof import('./../src/components/SimpleForm/index.vue')['default']
    SimpleTable: typeof import('./../src/components/SimpleTable/index.vue')['default']
  }
}
